# Generated by Django 4.2.7 on 2024-04-01 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profilpersonaliti", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quiz",
            name="AN",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="AS",
        ),
        migrations.AddField(
            model_name="question",
            name="AN",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="AS",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
