# Generated by Django 4.2.7 on 2024-08-14 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profilpersonaliti", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={"ordering": ["text", "question_number"]},
        ),
    ]
