# Generated by Django 4.2.7 on 2024-03-14 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profilpersonaliti', '0002_question_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profilpersonaliti.choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profilpersonaliti.question')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profilpersonaliti.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
