# Generated by Django 4.2.7 on 2024-08-14 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profilpersonaliti", "0003_alter_question_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={"ordering": ["text"]},
        ),
    ]
