# Generated by Django 4.2.7 on 2024-03-14 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profilpersonaliti', '0003_userresponse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userresponse',
            old_name='choice',
            new_name='selected_choice',
        ),
    ]
