# Generated by Django 4.2.7 on 2024-08-26 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profilpersonaliti", "0004_alter_question_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="question_number",
        ),
    ]
