# Generated by Django 4.2.7 on 2024-08-26 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profilpersonaliti", "0005_remove_question_question_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="question_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
