# Generated by Django 4.2.7 on 2023-11-23 12:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='sila masukkan nama penuh seperti dalam mykid', max_length=200, null=True, verbose_name='Nama')),
                ('no_tel', models.CharField(help_text='Masukkan No Telefon', max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='Nombor Telefon')),
                ('no_ic', models.CharField(help_text='Nombor mykid', max_length=12, verbose_name='No. My Kid')),
                ('email', models.EmailField(max_length=255)),
                ('jum_kelas', models.IntegerField(default=0, verbose_name='jumlah kelas')),
                ('jum_murid', models.IntegerField(default=0, verbose_name='Masukkan Jumlah Murid')),
                ('purata', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ListSekolah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_sek', models.CharField(max_length=255, verbose_name='Nama Sekolah')),
                ('kod_sekolah', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='TahunModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.CharField(choices=[('Pra Sekolah', 'Pra Sekolah'), ('Tahun 1', 'Tahun 1'), ('Tahun 2', 'Tahun 2'), ('Tahun 3', 'Tahun 3'), ('Tahun 4', 'Tahun 4'), ('Tahun 5', 'Tahun 5')], default='Tahun 1', max_length=11)),
            ],
        ),
    ]
