# Generated by Django 4.2.7 on 2024-01-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("utama", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Classroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "school",
                    models.CharField(
                        choices=[
                            ("SK KLANG", "SK KLANG"),
                            ("SK TELOK GADONG", "SK TELOK GADONG"),
                            ("SK PELABUHAN KLANG", "SK PELABUHAN KLANG"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "year",
                    models.CharField(
                        choices=[
                            ("PPKI", "PPKI"),
                            ("TAHUN1", "TAHUN1"),
                            ("TAHUN2", "TAHUN2"),
                            ("TAHUN3", "TAHUN3"),
                            ("TAHUN4", "TAHUN4"),
                            ("TAHUN5", "TAHUN5"),
                            ("TAHUN6", "TAHUN6"),
                        ],
                        max_length=10,
                    ),
                ),
                ("code_school", models.CharField(max_length=100)),
                ("purata", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="Info",
        ),
        migrations.DeleteModel(
            name="ListSekolah",
        ),
        migrations.DeleteModel(
            name="TahunModel",
        ),
    ]
