# Generated by Django 4.2.7 on 2023-11-21 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utama', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='catatan',
        ),
        migrations.RemoveField(
            model_name='info',
            name='category',
        ),
    ]
