# Generated by Django 4.2.7 on 2024-01-19 09:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("utama", "0002_classroom_delete_info_delete_listsekolah_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="classroom",
            old_name="purata",
            new_name="average",
        ),
    ]
