# Generated by Django 4.2.7 on 2023-11-24 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utama', '0002_info_tahun'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='list_sek',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utama.listsekolah', verbose_name='Senarai Sekolah'),
        ),
    ]
