# Generated by Django 4.2.7 on 2024-01-19 01:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("utama", "0002_classroom_delete_info_delete_listsekolah_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="code_school",
            field=models.CharField(max_length=100),
        ),
    ]
