# Generated by Django 4.2.7 on 2023-11-22 02:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utama', '0002_remove_info_catatan_remove_info_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='no_ic',
            field=models.CharField(help_text='Nombor MYKID', max_length=12),
        ),
        migrations.AlterField(
            model_name='info',
            name='no_tel',
            field=models.CharField(help_text='Masukkan No Telefon', max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
        ),
    ]
