# Generated by Django 4.2.7 on 2023-11-17 07:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('utama', '0002_info_delete_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='category',
        ),
        migrations.AddField(
            model_name='info',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='level_tingkatan',
            field=models.CharField(choices=[('TINGKATAN 1', 'Tingkatan 1'), ('TINGKATAN 2', 'Tingkatan 2'), ('TINGKATAN 3', 'Tingkatan 3'), ('TINGKATAN 4', 'Tingkatan 4'), ('TINGKATAN 5', 'Tingkatan 5')], default='TINGKATAN 1', max_length=12),
        ),
    ]
