# Generated by Django 4.2.7 on 2023-11-17 07:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('utama', '0003_remove_info_category_info_email_info_level_tingkatan'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='category',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
