# Generated by Django 4.2.7 on 2024-01-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("utama", "0003_rename_purata_classroom_average"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="average",
            field=models.IntegerField(null=True),
        ),
    ]
