# Generated by Django 4.2.7 on 2023-11-24 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utama', '0003_info_list_sek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tahunmodel',
            name='tahun',
            field=models.CharField(choices=[('Pra Sekolah', 'Pra Sekolah'), ('Tahun 1', 'Tahun 1'), ('Tahun 2', 'Tahun 2'), ('Tahun 3', 'Tahun 3'), ('Tahun 4', 'Tahun 4'), ('Tahun 5', 'Tahun 5')], default='Tahun 1', max_length=11, verbose_name='Tingkatan Tahun'),
        ),
    ]
