# Generated by Django 4.2.7 on 2023-11-23 08:31

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('utama', '0003_alter_info_no_ic_alter_info_no_tel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listsekolah',
            name='name',
        ),
        migrations.AddField(
            model_name='listsekolah',
            name='name_sek',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Nama Sekolah'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='info',
            name='jum_kelas',
            field=models.IntegerField(default=0, verbose_name='jumlah kelas'),
        ),
        migrations.AlterField(
            model_name='info',
            name='jum_murid',
            field=models.IntegerField(default=0, verbose_name='Masukkan Jumlah Murid'),
        ),
        migrations.AlterField(
            model_name='info',
            name='name',
            field=models.CharField(help_text='sila masukkan nama penuh seperti dalam mykid', max_length=200, null=True, verbose_name='Nama'),
        ),
        migrations.AlterField(
            model_name='info',
            name='no_ic',
            field=models.CharField(help_text='Nombor mykid', max_length=12, verbose_name='No. My Kid'),
        ),
        migrations.AlterField(
            model_name='info',
            name='no_tel',
            field=models.CharField(help_text='Masukkan No Telefon', max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='Nombor Telefon'),
        ),
    ]
