# Generated by Django 4.2.7 on 2023-11-24 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utama', '0004_alter_tahunmodel_tahun'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': 'Info', 'verbose_name_plural': 'Info'},
        ),
        migrations.AlterModelOptions(
            name='listsekolah',
            options={'verbose_name': 'Senarai Sekolah', 'verbose_name_plural': 'Senarai Sekolah'},
        ),
        migrations.AlterModelOptions(
            name='tahunmodel',
            options={'verbose_name': 'Tahun', 'verbose_name_plural': 'Tahun'},
        ),
        migrations.AlterField(
            model_name='info',
            name='jum_murid',
            field=models.IntegerField(default=0, verbose_name='Jumlah Murid'),
        ),
        migrations.AlterField(
            model_name='info',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Nama'),
        ),
    ]
