# Generated by Django 4.2.7 on 2023-11-23 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utama', '0004_remove_listsekolah_name_listsekolah_name_sek_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listsekolah',
            old_name='name_sek',
            new_name='nama_sek',
        ),
    ]
