# Generated by Django 4.2.7 on 2024-01-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("utama", "0004_alter_classroom_school"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="school",
            field=models.CharField(
                choices=[
                    ("SK KLANG", "SK KLANG"),
                    ("SK TELOK GADONG", "SK TELOK GADONG"),
                    ("SK PELABUHAN KLANG", "SK PELABUHAN KLANG"),
                ],
                max_length=50,
                verbose_name="Pilihan Sekolah",
            ),
        ),
    ]
