# Generated by Django 5.2.5 on 2025-08-21 08:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("utama", "0005_alter_classroom_school_alter_classroom_year"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Contact_us",
        ),
    ]
