# Generated by Django 4.2.7 on 2023-11-18 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utama', '0005_listsekolah'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='level_tingkatan',
            field=models.CharField(choices=[('PPKI', 'PPKI'), ('TAHUN 1', 'Tahun 1'), ('TAHUN 2', 'Tahun 2'), ('TAHUN 3', 'Tahun 3'), ('TAHUN 4', 'Tahun 4'), ('TAHUN 5', 'Tahun 5')], default='TAHUN 1', max_length=12),
        ),
    ]
