# Generated by Django 4.2.7 on 2024-01-29 06:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("utama", "0005_alter_classroom_school"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact_us",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.CharField(max_length=300)),
            ],
        ),
    ]
