# Generated by Django 5.2.5 on 2025-08-22 02:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("utama", "0006_delete_contact_us"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="latitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Latitude"),
        ),
        migrations.AddField(
            model_name="classroom",
            name="longtitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Longtitude"),
        ),
    ]
