# Generated by Django 4.2.7 on 2023-11-27 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utama', '0006_alter_tahunmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='list_kod_sekolah',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='info_list_kod_sekolah', to='utama.listsekolah'),
        ),
        migrations.AlterField(
            model_name='info',
            name='list_sek',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='info_list_sekolah', to='utama.listsekolah', verbose_name='Senarai Sekolah'),
        ),
    ]
