# Generated by Django 4.2.7 on 2023-11-18 07:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('utama', '0006_alter_info_level_tingkatan'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='catatan',
            field=models.TextField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='jum_kelas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='info',
            name='jumlah_murid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='info',
            name='purata',
            field=models.IntegerField(default=0),
        ),
    ]
