# Generated by Django 4.2.7 on 2024-01-29 08:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("utama", "0007_classroom_last_update"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="last_update",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
