# Generated by Django 5.2.5 on 2025-08-22 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("utama", "0007_classroom_latitude_classroom_longtitude"),
    ]

    operations = [
        migrations.RenameField(
            model_name="classroom",
            old_name="longtitude",
            new_name="longitude",
        ),
    ]
