# Generated by Django 4.2.7 on 2023-11-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utama', '0007_info_catatan_info_jum_kelas_info_jumlah_murid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='jumlah_murid',
            new_name='jum_murid',
        ),
        migrations.AlterField(
            model_name='info',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
