# Generated by Django 5.2.5 on 2025-08-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utama", "0008_rename_longtitude_classroom_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="school_photos/",
                verbose_name="Gambar Sekolah",
            ),
        ),
    ]
