# Generated by Django 4.2.7 on 2023-11-18 23:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('utama', '0008_rename_jumlah_murid_info_jum_murid_alter_info_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='listsekolah',
            name='kod_sekolah',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
