# Generated by Django 4.2.7 on 2023-11-19 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utama', '0009_listsekolah_kod_sekolah'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listsekolah',
            name='kod_sekolah',
        ),
    ]
