# Generated by Django 4.2.7 on 2024-01-30 04:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("utama", "0009_alter_classroom_last_update"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("school", models.CharField(max_length=100)),
            ],
        ),
    ]
