# Generated by Django 4.2.7 on 2023-11-27 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utama', '0009_alter_tahunmodel_tahun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tahunmodel',
            name='tahun',
            field=models.CharField(choices=[('PPKI', 'PPKI'), ('TAHUN SATU', 'TAHUN SATU'), ('TAHUN DUA', 'TAHUN DUA'), ('TAHUN TIGA', 'TAHUN TIGA'), ('TAHUN EMPAT', 'TAHUN EMPAT'), ('TAHUN LIMA', 'TAHUN LIMA'), ('TAHUN ENAM', 'TAHUN ENAM')], default='TAHUN 1', max_length=11, verbose_name='Tingkatan Tahun'),
        ),
    ]
