# Generated by Django 4.2.7 on 2023-12-01 03:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utama', '0010_alter_tahunmodel_tahun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='no_ic',
            field=models.CharField(max_length=12, verbose_name='No. My Kid'),
        ),
        migrations.AlterField(
            model_name='info',
            name='no_tel',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='Nombor Telefon'),
        ),
    ]
