# Generated by Django 4.2.7 on 2023-11-19 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utama', '0010_remove_listsekolah_kod_sekolah'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='level_tingkatan',
        ),
    ]
