# Generated by Django 4.2.7 on 2024-01-30 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("utama", "0010_searchlog"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="classroom",
            options={
                "verbose_name": "Enrolmen Sekolah",
                "verbose_name_plural": "Enrolmen Sekolah",
            },
        ),
        migrations.AlterModelOptions(
            name="contact_us",
            options={
                "verbose_name": "Maklum Balas",
                "verbose_name_plural": "Maklum Balas",
            },
        ),
        migrations.AlterField(
            model_name="classroom",
            name="average",
            field=models.IntegerField(verbose_name="purata"),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="year",
            field=models.CharField(
                choices=[
                    ("PPKI", "PPKI"),
                    ("TAHUN1", "TAHUN1"),
                    ("TAHUN2", "TAHUN2"),
                    ("TAHUN3", "TAHUN3"),
                    ("TAHUN4", "TAHUN4"),
                    ("TAHUN5", "TAHUN5"),
                    ("TAHUN6", "TAHUN6"),
                ],
                max_length=10,
                verbose_name="tahun kelas",
            ),
        ),
        migrations.AlterField(
            model_name="contact_us",
            name="message",
            field=models.CharField(max_length=300, verbose_name="mesej"),
        ),
        migrations.AlterField(
            model_name="contact_us",
            name="name",
            field=models.CharField(max_length=200, verbose_name="nama"),
        ),
    ]
