# Generated by Django 4.2.7 on 2023-12-05 03:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("utama", "0011_alter_info_no_ic_alter_info_no_tel"),
    ]

    operations = [
        migrations.AddField(
            model_name="info",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="info",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
