# Generated by Django 4.2.7 on 2023-11-19 06:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('utama', '0012_tahunlevel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TahunLevel',
        ),
        migrations.AddField(
            model_name='info',
            name='tahun',
            field=models.CharField(choices=[('0', 'Pra Sekolah'), ('1', 'Tahun 1'), ('2', 'Tahun 2'), ('3', 'Tahun 3'), ('4', 'Tahun 4'), ('5', 'Tahun 5')], default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
    ]
