# Generated by Django 4.2.7 on 2024-01-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("utama", "0012_searchlog_timestamp_searchlog_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchlog",
            name="hits",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
