# Generated by Django 5.2.8 on 2025-12-08 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utama", "0012_alter_classroom_school"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="year",
            field=models.CharField(
                choices=[
                    ("PPKI", "PPKI"),
                    ("TAHUN SATU", "TAHUN SATU"),
                    ("TAHUN DUA", "TAHUN DUA"),
                    ("TAHUN TIGA", "TAHUN TIGA"),
                    ("TAHUN EMPAT", "TAHUN EMPAT"),
                    ("TAHUN LIMA", "TAHUN LIMA"),
                    ("TAHUN ENAM", "TAHUN ENAM"),
                    ("PERALIHAN", "PERALIHAN"),
                    ("TINGKATAN SATU", "TINGKATAN SATU"),
                    ("TINGKATAN DUA", "TINGKATAN DUA"),
                    ("TINGKATAN TIGA", "TINGKATAN TIGA"),
                    ("TINGKATAN EMPAT", "TINGKATAN EMPAT"),
                    ("TINGKATAN LIMA", "TINGKATAN LIMA"),
                    ("TINGKATAN ENAM ATAS", "TINGKATAN ENAM ATAS"),
                    ("TINGKATAN ENAM BAWAH", "TINGKATAN ENAM BAWAH"),
                ],
                max_length=50,
                verbose_name="Masukkan tahun kelas",
            ),
        ),
    ]
