# Generated by Django 4.2.7 on 2024-01-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("utama", "0013_alter_tahunmodel_tahun"),
    ]

    operations = [
        migrations.AlterField(
            model_name="info",
            name="email",
            field=models.EmailField(max_length=255, verbose_name="E-Mail"),
        ),
        migrations.AlterField(
            model_name="info",
            name="name",
            field=models.CharField(max_length=150, null=True, verbose_name="Nama"),
        ),
        migrations.AlterField(
            model_name="info",
            name="no_ic",
            field=models.CharField(max_length=12, verbose_name="No. MYKID"),
        ),
    ]
