# Generated by Django 4.2.7 on 2024-01-30 08:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("utama", "0013_searchlog_hits"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SearchLog",
        ),
    ]
