# Generated by Django 4.2.7 on 2024-01-31 01:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("utama", "0014_delete_searchlog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classroom",
            name="last_update",
        ),
    ]
