# Generated by Django 4.2.7 on 2024-01-15 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("utama", "0014_alter_info_email_alter_info_name_alter_info_no_ic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="info",
            name="tahun",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="utama.tahunmodel",
                verbose_name="Tahun(Darjah)",
            ),
        ),
    ]
