# Generated by Django 4.2.7 on 2024-01-16 03:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("utama", "0015_alter_info_tahun"),
    ]

    operations = [
        migrations.CreateModel(
            name="Classroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_school", models.CharField(max_length=50)),
                ("capacity", models.IntegerField()),
            ],
        ),
    ]
