# Generated by Django 4.2.7 on 2023-11-19 09:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('utama', '0015_rename_tahun_tahunmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='listsekolah',
            name='kod_sekolah',
            field=models.CharField(default=django.utils.timezone.now, max_length=8),
            preserve_default=False,
        ),
    ]
