# Generated by Django 5.2.8 on 2025-12-08 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utama", "0015_alter_classroom_school"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="year",
            field=models.CharField(
                choices=[
                    ("PPKI", "PPKI"),
                    ("TAHUN SATU", "TAHUN 1"),
                    ("TAHUN DUA", "TAHUN 2"),
                    ("TAHUN TIGA", "TAHUN 3"),
                    ("TAHUN EMPAT", "TAHUN 4"),
                    ("TAHUN LIMA", "TAHUN 5"),
                    ("TAHUN ENAM", "TAHUN 6"),
                    ("PERALIHAN", "PERALIHAN"),
                    ("TINGKATAN SATU", "TINGKATAN SATU"),
                    ("TINGKATAN 2", "TINGKATAN DUA"),
                    ("TINGKATAN 3", "TINGKATAN TIGA"),
                    ("TINGKATAN 4", "TINGKATAN EMPAT"),
                    ("TINGKATAN 5", "TINGKATAN LIMA"),
                    ("TINGKATAN ENAM ATAS", "TINGKATAN ENAM ATAS"),
                    ("TINGKATAN ENAM BAWAH", "TINGKATAN ENAM BAWAH"),
                ],
                max_length=50,
                verbose_name="Masukkan tahun kelas",
            ),
        ),
    ]
