# Generated by Django 4.2.7 on 2024-01-18 08:37

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("utama", "0016_classroom"),
    ]

    operations = [
        migrations.RenameField(
            model_name="classroom",
            old_name="capacity",
            new_name="purata",
        ),
        migrations.RemoveField(
            model_name="classroom",
            name="name_school",
        ),
        migrations.AddField(
            model_name="classroom",
            name="school",
            field=models.CharField(
                choices=[
                    ("SK KLANG", "SK KLANG"),
                    ("SK TELOK GADONG", "SK TELOK GADONG"),
                    ("SK PELABUHAN KLANG", "SK PELABUHAN KLANG"),
                ],
                default=datetime.datetime(
                    2024, 1, 18, 8, 37, 20, 798754, tzinfo=datetime.timezone.utc
                ),
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="classroom",
            name="year",
            field=models.CharField(
                choices=[
                    ("PPKI", "PPKI"),
                    ("TAHUN1", "TAHUN1"),
                    ("TAHUN2", "TAHUN2"),
                    ("TAHUN3", "TAHUN3"),
                    ("TAHUN4", "TAHUN4"),
                    ("TAHUN5", "TAHUN5"),
                    ("TAHUN6", "TAHUN6"),
                ],
                default=django.utils.timezone.now,
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Info",
        ),
        migrations.DeleteModel(
            name="ListSekolah",
        ),
        migrations.DeleteModel(
            name="TahunModel",
        ),
    ]
