# Generated by Django 4.2.7 on 2024-02-22 03:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("utama", "0017_alter_classroom_average_alter_classroom_school_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="average",
            field=models.IntegerField(verbose_name="purata"),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="school",
            field=models.CharField(
                choices=[
                    ("SK KLANG", "SK KLANG"),
                    ("SK TELOK GADONG", "SK TELOK GADONG"),
                    ("SK PELABUHAN KLANG", "SK PELABUHAN KLANG"),
                    ("SK BUKIT KAPAR", "SK BUKIT KAPAR"),
                ],
                max_length=50,
                verbose_name="Pilihan Sekolah",
            ),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="year",
            field=models.CharField(
                choices=[
                    ("PPKI", "PPKI"),
                    ("TAHUN1", "TAHUN1"),
                    ("TAHUN2", "TAHUN2"),
                    ("TAHUN3", "TAHUN3"),
                    ("TAHUN4", "TAHUN4"),
                    ("TAHUN5", "TAHUN5"),
                    ("TAHUN6", "TAHUN6"),
                ],
                max_length=10,
                verbose_name="tahun kelas",
            ),
        ),
    ]
