# Generated by Django 5.2.8 on 2025-12-08 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utama", "0017_alter_classroom_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="school",
            field=models.CharField(
                choices=[
                    ("SK KLANG", "SK KLANG"),
                    ("SK TELOK GADONG", "SK TELOK GADONG"),
                    ("SK PELABUHAN KELANG", "SK PELABUHAN KELANG"),
                    ("SK TELOK MENEGON", "SK TELOK MENEGON"),
                    ("SK BUKIT NAGA", "SK BUKIT NAGA "),
                    ("SK JALAN KEBUN", "SK JALAN KEBUN"),
                    ("SK BATU BELAH", "SK BATU BELAH"),
                    ("SK SEMENTA ", "SK SEMENTA"),
                    ("SK KAPAR", "SK KAPAR"),
                    ("SK BUKIT KAPAR", "SK BUKIT KAPAR"),
                    ("SK SUNGAI BINJAI", "SK SUNGAI BINJAI"),
                    ("SK PULAU INDAH", "SK PULAU INDAH"),
                    ("SK TOK MUDA", "SK TOK MUDA"),
                    ("SK BUKIT KUDA", "SK BUKIT KUDA"),
                    ("SK PANDAMARAN JAYA", "SK PANDAMARAN JAYA"),
                    ("SK KG JOHAN SETIA", "SK KG JOHAN SETIA"),
                    ("SK SUNGAI SERDANG", "SK SUNGAI SERDANG"),
                    ("SK KG PENDAMAR", "SK KG PENDAMAR"),
                    ("SK TELOK GONG", "SK TELOK GONG"),
                    ("SK TAMAN KLANG JAYA", "SK TAMAN KLANG JAYA"),
                    ("SK SUNGAI UDANG", "SK SUNGAI UDANG"),
                    ("SK PELABUHAN UTARA", "SK PELABUHAN UTARA"),
                    ("SK ABDUL SAMAT", "SK ABDUL SAMAT"),
                    ("SK MERU", "SK MERU"),
                    ("SK KAMPUNG IDAMAN", "SK KAMPUNG IDAMAN"),
                    ("SK TAMAN KLANG UTAMA", "SK TAMAN KLANG UTAMA"),
                    ("SK KAMPUNG JAWA", "SK KAMPUNG JAWA"),
                    ("SK TAMAN GEMBIRA", "SK TAMAN GEMBIRA"),
                    ("SK BUKIT TINGGI ", "SK BUKIT TINGGI"),
                    ("SK BUKIT KEMUNING 2", "SK BUKIT KEMUNING 2"),
                    ("SK MERU (2)", "SK MERU (2)"),
                    ("SK SUNGAI KAPAR INDAH", "SK SUNGAI KAPAR INDAH"),
                    ("SK KOTA KEMUNING", "SK KOTA KEMUNING "),
                    ("SK PULAU INDAH (2)", "SK PULAU INDAH (2)"),
                    ("SK BUKIT RIMAU ", "SK BUKIT RIMAU"),
                    ("SK BUKIT CERAKAH ", "SK BUKIT CERAKAH"),
                    ("SK METHODIST ACS", "SK METHODIST ACS"),
                    ("SK (1) JALAN BATU TIGA", "SK (1) JALAN BATU TIGA "),
                    ("SK CONVENT (1) (M)", "SK CONVENT (1) (M) "),
                    ("SK CONVENT (2) (M)  ", "SK CONVENT (2) (M)"),
                    ("SK (1) JALAN MERU", "SK (1) JALAN MERU "),
                    ("SK (2) JALAN MERU", "SK (2) JALAN MERU "),
                    ("SK METHODIST ( M )", "SK METHODIST ( M )"),
                    ("SK (P) METHODIST MGS", "SK (P) METHODIST MGS "),
                    ("SK TENGKU BENDAHARA AZMAN (1)", "SK TENGKU BENDAHARA AZMAN (1)"),
                    ("SK TENGKU BENDAHARA AZMAN (2) ", "SK TENGKU BENDAHARA AZMAN (2)"),
                    ("SK (P) BUKIT KUDA", "SK (P) BUKIT KUDA"),
                    ("SK (2) SIMPANG LIMA ", "SK (2) SIMPANG LIMA      "),
                    ("SK ST ANNE'S CONVENT", "SK ST ANNE'S CONVENT"),
                    ("SJK(C) PEREMPUAN", "SJK(C) PEREMPUAN"),
                    ("SJK(C) CHUEN MIN", "SJK(C) CHUEN MIN"),
                    ("SJK(C) CHUNG HUA", "SJK(C) CHUNG HUA "),
                    ("SJK(C) HIN HUA ", "SJK(C) HIN HUA "),
                    ("SJK(C) HWA LIEN", "SJK(C) HWA LIEN"),
                    ("SJK(C) KHE BENG", "SJK(C) KHE BENG"),
                    ("SJK(C) KONG HOE", "SJK(C) KONG HOE"),
                    ("SJK(C) LEE MIN", "SJK(C) LEE MIN"),
                    ("SJK(C) PANDAMARAN 'A'", "SJK(C) PANDAMARAN 'A'"),
                    ("SJK(C) PANDAMARAN 'B'", "SJK(C) PANDAMARAN 'B'"),
                    ("SJK(C) PIN HWA (1)", "SJK(C) PIN HWA (1)"),
                    ("SJK(C) PUI YING", "SJK(C) PUI YING"),
                    ("SJK(C) SOO JIN", "SJK(C) SOO JIN"),
                    ("SJK(C) TIONG HUA KOK BIN", "SJK(C) TIONG HUA KOK BIN"),
                    ("SJK(C) TSHING NIAN", "SJK(C) TSHING NIAN"),
                    ("SJK(C) WU TECK ", "SJK(C) WU TECK"),
                    ("SJK(C) YING WAH", "SJK(C) YING WAH "),
                    ("SJK(C) PIN HWA (2)", "SJK(C) PIN HWA (2) "),
                    ("SJK(C) TAMAN RASHNA", "SJK(C) TAMAN RASHNA"),
                    ("SJK(T) LADANG BRAFFERTON", "SJK(T) LADANG BRAFFERTON"),
                    ("SJK(T) LADANG BUKIT RAJAH", "SJK(T) LADANG BUKIT RAJAH"),
                    ("SJK(T) LADANG EMERALD", "SJK(T) LADANG EMERALD"),
                    ("SJK(T) LADANG HIGHLANDS", "SJK(T) LADANG HIGHLANDS "),
                    ("SJK(T) LADANG JALAN ACOB ", "SJK(T) LADANG JALAN ACOB "),
                    ("SJK(T) JALAN TEPI SUNGAI", "SJK(T) JALAN TEPI SUNGAI"),
                    ("SJK(T) JALAN MERU", "SJK(T) JALAN MERU"),
                    ("SJK(T) METHODIST", "SJK(T) METHODIST "),
                    ("SJK(T) SIMPANG LIMA", "SJK(T) SIMPANG LIMA"),
                    ("SJK(T) LDG VALLAMBROSA", "SJK(T) LDG VALLAMBROSA "),
                    ("SJK(T) TAMAN SENTOSA", "SJK(T) TAMAN SENTOSA"),
                    ("SJK(T) LADANG NORTH HUMMOCK", "SJK(T) LADANG NORTH HUMMOCK"),
                    (
                        "SEKOLAH MENENGAH KEBANGSAAN RAJA MAHADI",
                        "SEKOLAH MENENGAH KEBANGSAAN RAJA MAHADI",
                    ),
                    (
                        "SEKOLAH MENENGAH KEBANGSAAN RAJA LUMU",
                        "SEKOLAH MENENGAH KEBANGSAAN RAJA LUMU",
                    ),
                    (
                        "SEKOLAH MENENGAH KEBANGSAAN TENGKU AMPUAN RAHIMAH",
                        "SEKOLAH MENENGAH KEBANGSAAN TENGKU AMPUAN RAHIMAH",
                    ),
                    (
                        "SEKOLAH MENENGAH KEBANGSAAN TENGKU AMPUAN JEMAAH",
                        "SEKOLAH MENENGAH KEBANGSAAN TENGKU AMPUAN JEMAAH",
                    ),
                    (
                        "SEKOLAH MENENGAH KEBANGSAAN TENGKU IDRIS SHAH",
                        "SEKOLAH MENENGAH KEBANGSAAN TENGKU IDRIS SHAH",
                    ),
                    (
                        "SEKOLAH MENENGAH KEBANGSAAN SULTAN ABDUL SAMAD",
                        "SEKOLAH MENENGAH KEBANGSAAN SULTAN ABDUL SAMAD",
                    ),
                    (
                        "SEKOLAH MENENGAH KEBANGSAAN PULAU INDAH",
                        "SEKOLAH MENENGAH KEBANGSAAN PULAU INDAH",
                    ),
                    (
                        "KOLEJ TINGKATAN ENAM SRI ISTANA",
                        "KOLEJ TINGKATAN ENAM SRI ISTANA",
                    ),
                    (
                        "SEKOLAH MENENGAH KEBANGSAAN RANTAU PANJANG",
                        "SEKOLAH MENENGAH KEBANGSAAN RANTAU PANJANG",
                    ),
                    (
                        "SEKOLAH MENENGAH KEBANGSAAN (P) KAPAR",
                        "SEKOLAH MENENGAH KEBANGSAAN (P) KAPAR",
                    ),
                    (
                        "SEKOLAH MENENGAH KEBANGSAAN PENDAMARAN JAYA",
                        "SEKOLAH MENENGAH KEBANGSAAN PENDAMARAN JAYA",
                    ),
                    (
                        "SEKOLAH MENENGAH KEBANGSAAN TELOK GADONG",
                        "SEKOLAH MENENGAH KEBANGSAAN TELOK GADONG",
                    ),
                    (
                        "SEKOLAH MENENGAH KEBANGSAAN SRI ANDALAS",
                        "SEKOLAH MENENGAH KEBANGSAAN SRI ANDALAS",
                    ),
                    (
                        "SEKOLAH MENENGAH KEBANGSAAN JALAN KEBUN",
                        "SEKOLAH MENENGAH KEBANGSAAN JALAN KEBUN",
                    ),
                    (
                        "SEKOLAH MENENGAH KEBANGSAAN KAMPUNG JAWA",
                        "SEKOLAH MENENGAH KEBANGSAAN KAMPUNG JAWA",
                    ),
                    (
                        "SEKOLAH MENENGAH KEBANGSAAN TAMAN KLANG UTAMA",
                        "SEKOLAH MENENGAH KEBANGSAAN TAMAN KLANG UTAMA",
                    ),
                    (
                        "SEKOLAH MENENGAH KEBANGSAAN KOTA KEMUNING",
                        "SEKOLAH MENENGAH KEBANGSAAN KOTA KEMUNING",
                    ),
                    (
                        "SEKOLAH MENENGAH KEBANGSAAN BANDAR BARU SULTAN SULEIMAN",
                        "SEKOLAH MENENGAH KEBANGSAAN BANDAR BARU SULTAN SULEIMAN",
                    ),
                    (
                        "SEKOLAH MENENGAH KEBANGSAAN SUNGAI KAPAR INDAH",
                        "SEKOLAH MENENGAH KEBANGSAAN SUNGAI KAPAR INDAH",
                    ),
                    (
                        "SEKOLAH MENENGAH KEBANGSAAN SHAHBANDARAYA",
                        "SEKOLAH MENENGAH KEBANGSAAN SHAHBANDARAYA",
                    ),
                    (
                        "SEKOLAH MENENGAH KEBANGSAAN BATU UNJUR",
                        "SEKOLAH MENENGAH KEBANGSAAN BATU UNJUR",
                    ),
                    (
                        "SEKOLAH MENENGAH KEBANGSAAN BUKIT TINGGI KLANG",
                        "SEKOLAH MENENGAH KEBANGSAAN BUKIT TINGGI KLANG",
                    ),
                    (
                        "SEKOLAH MENENGAH KEBANGSAAN BUKIT KAPAR",
                        "SEKOLAH MENENGAH KEBANGSAAN BUKIT KAPAR",
                    ),
                    (
                        "SEKOLAH MENENGAH KEBANGSAAN METHODIST (ACS)",
                        "SEKOLAH MENENGAH KEBANGSAAN METHODIST (ACS)",
                    ),
                    (
                        "SEKOLAH MENENGAH KEBANGSAAN CHUNG HWA",
                        "SEKOLAH MENENGAH KEBANGSAAN CHUNG HWA",
                    ),
                    (
                        "SEKOLAH MENENGAH KEBANGSAAN CONVENT",
                        "SEKOLAH MENENGAH KEBANGSAAN CONVENT",
                    ),
                    (
                        "SEKOLAH MENENGAH KEBANGSAAN TINGGI KLANG",
                        "SEKOLAH MENENGAH KEBANGSAAN TINGGI KLANG",
                    ),
                    (
                        "SEKOLAH MENENGAH KEBANGSAAN KWANG HUA",
                        "SEKOLAH MENENGAH KEBANGSAAN KWANG HUA",
                    ),
                    (
                        "SEKOLAH MENENGAH KEBANGSAAN LA SALLE",
                        "SEKOLAH MENENGAH KEBANGSAAN LA SALLE",
                    ),
                    (
                        "SEKOLAH MENENGAH KEBANGSAAN (P) METHODIST",
                        "SEKOLAH MENENGAH KEBANGSAAN (P) METHODIST",
                    ),
                    (
                        "SEKOLAH MENENGAH KEBANGSAAN (P) BUKIT KUDA",
                        "SEKOLAH MENENGAH KEBANGSAAN (P) BUKIT KUDA",
                    ),
                    (
                        "SEKOLAH MENENGAH KEBANGSAAN DATO HAMZAH",
                        "SEKOLAH MENENGAH KEBANGSAAN DATO HAMZAH",
                    ),
                    (
                        "SEKOLAH MENENGAH KEBANGSAAN (P) RAJA ZARINA",
                        "SEKOLAH MENENGAH KEBANGSAAN (P) RAJA ZARINA",
                    ),
                    (
                        "SEKOLAH MENENGAH KEBANGSAAN MERU",
                        "SEKOLAH MENENGAH KEBANGSAAN MERU",
                    ),
                    (
                        "SEKOLAH MENENGAH KEBANGSAAN PULAU KETAM",
                        "SEKOLAH MENENGAH KEBANGSAAN PULAU KETAM",
                    ),
                    ("SAMT SULTAN HISAMUDDIN", "SAMT SULTAN HISAMUDDIN"),
                    ("SAM HISAMUDDIN", "SAM HISAMUDDIN"),
                    ("SAM NURUL IMAN", "SAM NURUL IMAN"),
                    ("KOLEJ VOKASIONAL KLANG", "KOLEJ VOKASIONAL KLANG"),
                    ("KOLEJ ISLAM SULTAN ALAM SHAH", "KOLEJ ISLAM SULTAN ALAM SHAH"),
                ],
                max_length=100,
                verbose_name="Senarai Sekolah",
            ),
        ),
    ]
