# Generated by Django 4.2.7 on 2023-11-23 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utama', '0005_rename_name_sek_listsekolah_nama_sek'),
        ('utama', '0018_alter_tahunmodel_tahun'),
    ]

    operations = [
    ]
