# Generated by Django 5.2.8 on 2025-12-09 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utama", "0018_alter_classroom_school"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="year",
            field=models.CharField(
                choices=[
                    ("PPKI", "PPKI"),
                    ("TAHUN SATU", "TAHUN 1"),
                    ("TAHUN DUA", "TAHUN 2"),
                    ("TAHUN TIGA", "TAHUN 3"),
                    ("TAHUN EMPAT", "TAHUN 4"),
                    ("TAHUN LIMA", "TAHUN 5"),
                    ("TAHUN ENAM", "TAHUN 6"),
                    ("PERALIHAN", "PERALIHAN"),
                    ("PERALIHAN", "PERALIHAN"),
                    ("TINGKATAN 1", "TINGKATAN 1"),
                    ("TINGKATAN 2", "TINGKATAN 2"),
                    ("TINGKATAN 3", "TINGKATAN 3"),
                    ("TINGKATAN 4", "TINGKATAN 4"),
                    ("TINGKATAN 5", "TINGKATAN 5"),
                    ("TINGKATAN 6 ATAS", "TINGKATAN 6 ATAS"),
                    ("TINGKATAN 6 BAWAH", "TINGKATAN 6 BAWAH"),
                    ("TAHUN 1 KOLEJ VOKASIONAL", "TAHUN 1 KOLEJ VOKASIONAL"),
                    ("TAHUN 2 KOLEJ VOKASIONAL", "TAHUN 1 KOLEJ VOKASIONAL"),
                    ("TAHUN 3 KOLEJ VOKASIONAL", "TAHUN 1 KOLEJ VOKASIONAL"),
                    ("TAHUN 4 KOLEJ VOKASIONAL", "TAHUN 1 KOLEJ VOKASIONAL"),
                ],
                max_length=50,
                verbose_name="Masukkan tahun kelas",
            ),
        ),
    ]
