# Generated by Django 5.2.5 on 2025-08-28 08:31

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nama Sekolah')),
                ('address', models.TextField(blank=True, verbose_name='Alamat Penuh')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Koordinat Lokasi')),
            ],
            options={
                'verbose_name': 'Sekolah',
                'verbose_name_plural': 'Senarai Sekolah',
            },
        ),
    ]
