# Generated by Django 5.2.5 on 2025-08-29 01:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carian_sekolah", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="school_type",
            field=models.CharField(
                choices=[
                    ("RENDAH", "Sekolah Rendah"),
                    ("MENENGAH", "Sekolah Menengah"),
                ],
                default="RENDAH",
                max_length=10,
                verbose_name="Jenis Sekolah",
            ),
        ),
    ]
