# Generated by Django 5.2.5 on 2025-09-03 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carian_sekolah', '0003_school_kod_sekolah_school_ppd'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='passcode',
            field=models.CharField(blank=True, max_length=10, verbose_name='Poskod'),
        ),
    ]
