# Generated by Django 5.2.5 on 2025-09-03 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carian_sekolah', '0004_school_passcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='passcode',
            new_name='postcode',
        ),
    ]
