# Generated by Django 5.2.5 on 2025-09-03 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carian_sekolah', '0007_school_postcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='postcode',
        ),
    ]
