# Generated by Django 5.2.5 on 2025-09-03 07:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("carian_sekolah", "0009_ppd"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PPD",
        ),
    ]
