# Generated by Django 5.2.5 on 2025-09-11 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carian_sekolah", "0010_delete_ppd"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolImageSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="submissions/", verbose_name="Gambar yang dimuat naik"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Menunggu Kelulusan"),
                            ("APPROVE", "diluluskan"),
                            ("REJECTED", "Ditolak"),
                        ],
                        default="PENDING",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Tarikh dimuat naik"
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="carian_sekolah.school",
                        verbose_name="sekolah",
                    ),
                ),
            ],
            options={
                "verbose_name": "serahan gambar sekolah",
                "verbose_name_plural": "serahan gambar sekolah",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
