# Generated by Django 5.2.5 on 2025-09-11 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carian_sekolah", "0011_schoolimagesubmission"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="postcode",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Poskod"
            ),
        ),
    ]
