# Generated by Django 5.2.5 on 2025-09-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carian_sekolah", "0012_school_postcode"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="schoolimagesubmission",
            options={
                "ordering": ["-uploaded_at"],
                "verbose_name": "Serahan Gambar Sekolah",
                "verbose_name_plural": "Serahan Gambar Sekolah",
            },
        ),
        migrations.AddField(
            model_name="school",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="school_photos/",
                verbose_name="Gambar Utama Sekolah",
            ),
        ),
        migrations.AlterField(
            model_name="schoolimagesubmission",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Menunggu Kelulusan"),
                    ("APPROVED", "Diluluskan"),
                    ("REJECTED", "Ditolak"),
                ],
                default="PENDING",
                max_length=10,
                verbose_name="status",
            ),
        ),
    ]
