# Generated by Django 5.2.5 on 2025-10-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "carian_sekolah",
            "0013_alter_schoolimagesubmission_options_school_photo_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Name",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kod_sekolah",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        unique=True,
                        verbose_name="kod sekolah",
                    ),
                ),
            ],
        ),
    ]
