# Generated by Django 6.0.1 on 2026-01-16 13:31

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carian_sekolah', '0014_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Name',
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['name'], 'verbose_name': 'Sekolah', 'verbose_name_plural': 'Senarai Sekolah'},
        ),
        migrations.AlterModelOptions(
            name='schoolimagesubmission',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Serahan Gambar', 'verbose_name_plural': 'Senarai Serahan Gambar'},
        ),
        migrations.AlterField(
            model_name='school',
            name='kod_sekolah',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True, unique=True, verbose_name='Kod Sekolah'),
        ),
        migrations.AlterField(
            model_name='school',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, help_text='Format automatik dari sistem GPS', srid=4326, verbose_name='Koordinat Lokasi'),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Nama Sekolah'),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_type',
            field=models.CharField(choices=[('RENDAH', 'Sekolah Rendah'), ('MENENGAH', 'Sekolah Menengah')], db_index=True, default='RENDAH', max_length=10, verbose_name='Jenis Sekolah'),
        ),
        migrations.AlterField(
            model_name='schoolimagesubmission',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='carian_sekolah.school', verbose_name='Sekolah'),
        ),
        migrations.AlterField(
            model_name='schoolimagesubmission',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Menunggu Kelulusan'), ('APPROVED', 'Diluluskan'), ('REJECTED', 'Ditolak')], default='PENDING', max_length=10, verbose_name='Status Kelulusan'),
        ),
    ]
