# Generated by Django 6.0.1 on 2026-01-17 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carian_sekolah', '0015_delete_name_alter_school_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='postcode',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Poskod'),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_type',
            field=models.CharField(db_index=True, default='RENDAH', max_length=12, verbose_name='Jenis Sekolah'),
        ),
    ]
