# Generated by Django 6.0.1 on 2026-01-17 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carian_sekolah', '0016_alter_school_postcode_alter_school_school_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Bandar'),
        ),
    ]
