# Generated by Django 6.0.1 on 2026-01-17 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carian_sekolah', '0017_school_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='postcode',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Poskod'),
        ),
    ]
