# Generated by Django 6.0.1 on 2026-01-17 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carian_sekolah', '0019_alter_school_school_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_type',
            field=models.CharField(db_index=True, default='SK', max_length=50, verbose_name='Jenis Sekolah'),
        ),
    ]
