# Generated by Django 6.0.1 on 2026-01-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carian_sekolah', '0022_alter_school_postcode_alter_school_ppd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_type',
            field=models.CharField(choices=[('SK', 'Sekolah Kebangsaan (SK)'), ('SJK(C)', 'SJK Cina'), ('SJK(T)', 'SJK Tamil'), ('SMK', 'Sekolah Menengah Kebangsaan'), ('SMJK', 'Sekolah Menengah Jenis Kebangsaan'), ('SABK', 'Sekolah Agama Bantuan Kerajaan'), ('SMK Agama', 'Sekolah Menengah Kebangsaan Agama MAAHAD'), ('KOLEJ', 'Kolej Tingkatan 6'), ('KV', 'Kolej Vokasional'), ('SM', 'Sekolah Menengah'), ('LAIN', 'Lain-lain')], db_index=True, default='SK', max_length=50, verbose_name='Jenis Sekolah'),
        ),
    ]
