# Generated by Django 6.0.1 on 2026-01-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carian_sekolah', '0027_alter_school_school_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_type',
            field=models.CharField(choices=[('SK', 'Sekolah Kebangsaan (SK)'), ('SJK(C)', 'SJK Cina'), ('SJK(T)', 'SJK Tamil'), ('SMK', 'Sekolah Menengah Kebangsaan'), ('SMJK', 'Sekolah Menengah Jenis Kebangsaan'), ('SM Agama (SABK)', 'SM Agama (SABK)'), ('SMK Agama', 'Sekolah Menengah Kebangsaan Agama MAAHAD'), ('Kolej Tingkatan 6', 'Kolej Tingkatan 6'), ('KV', 'Kolej Vokasional'), ('SMBP', 'SM Berasrama Penuh'), ('SK(ASLI)', 'SK Asli'), ('LAIN', 'Lain-lain')], db_index=True, default='SK', max_length=50, verbose_name='Jenis Sekolah'),
        ),
    ]
