# Generated by Django 4.2.7 on 2024-12-09 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={"verbose_name": "Tempahan", "verbose_name_plural": "Tempahan"},
        ),
        migrations.AlterModelOptions(
            name="room",
            options={
                "ordering": ["name"],
                "verbose_name": "Bilik",
                "verbose_name_plural": "Bilik",
            },
        ),
        migrations.AlterModelOptions(
            name="timeslot",
            options={
                "verbose_name": "Masa Tempahan",
                "verbose_name_plural": "Masa Tempahan",
            },
        ),
    ]
