# Generated by Django 4.2.7 on 2024-11-28 04:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_booking_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="room",
            options={"ordering": ["name"]},
        ),
        migrations.RenameField(
            model_name="room",
            old_name="available",
            new_name="booked",
        ),
        migrations.RemoveField(
            model_name="room",
            name="capacity",
        ),
        migrations.RemoveField(
            model_name="room",
            name="description",
        ),
        migrations.AddField(
            model_name="room",
            name="advance_booking",
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="room",
            name="name",
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name="Booking",
        ),
    ]
